### ISSUE TITLE
Missing url in text

### ISSUE THREAD

**Issue by Thomasdezeeuw** [kubernetesbootcamp/kubernetes-bootcamp#2]
On the following line: https://github.com/kubernetesbootcamp/kubernetes-bootcamp/blob/008edc3d529fd44a69b2b0ce07c65e68f25c5e3f/2-1.html#L276, at the end of the line.

It contains the literal text `[url to github repo]`.

**Comment by lpil** [comment]
Came here to post the same thing :)

**Comment by radu-matei** [comment]
Again, came here to post the same :)
